name: Run Python Script Every 2 Minutes and Manual Trigger

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  run_python_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install feedparser
          pip install secure-smtplib

      - name: Output next run time
        run: |
          next_run=$(date -d '+15 minutes' +'%Y-%m-%d %H:%M:%S')
          echo "Next run time: $next_run" > next_run_time.txt
          echo "Next run time: $next_run"

      - name: Execute Python script
        run: python Pontosparavoar.py
