name: Run Python Script Every 2 Hours and Manual Trigger

on:
  schedule:
    - cron: '0 */2 * * *'  # Rodar a cada 2 horas
  workflow_dispatch:  # Trigger manual

jobs:
  run_python_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install feedparser
          pip install secure-smtplib

      - name: Determine next run time
        id: next_run_time
        run: echo "::set-output name=next_run_time::$(date -u +'%Y-%m-%dT%H:%M:%SZ' -d '+2 hours')"

      - name: Output next run time
        run: echo "Next run time: ${{ steps.next_run_time.outputs.next_run_time }}"

      - name: Execute Python script
        run: python Pontosparavoar.py "${{ steps.next_run_time.outputs.next_run_time }}"
