name: Run Python Script Every 2 Minutes and Manual Trigger

on:
  schedule:
 - cron: '0 */2 * * *'  # Ação agendada para rodar a cada 2 horas
  workflow_dispatch:  # Acionamento manual do fluxo de trabalho
  
jobs:
  run_python_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install feedparser
          pip install secure-smtplib

      - name: Determine next run time
        run: |
          next_run_time=$(date -u +"%Y-%m-%dT%H:%M:%SZ" -d '+15 minutes')
          if echo "$next_run_time" > next_run_time.txt; then
            echo "Next run time: $next_run_time"
          else
            echo "Error: Failed to create next_run_time.txt file."
            exit 1
          fi

      - name: Show next run time
        run: cat next_run_time.txt

      - name: Execute Python script
        run: python Pontosparavoar.py
