name: Manual Run Python Script

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  run_python_script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
      pip install feedparser
      pip install requests
      pip install beautifulsoup4
      pip install google-generativeai
      
    - name: Execute Python script
      run: python PythonTest.py  # Replace 'PythonTest.py' with the name of your Python script
